apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
    - name: goserver-service
      protocol: TCP
      port: 8000 # Port on the service
      targetPort: 80 # Port on the container
